apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/galaxytiger/cis-92:milestone-5.2
    ports:
    - containerPort: 80
    env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: mysite-secret
          key: SECRET_KEY
    - name: PORT
      value: "80"
    - name: DB_ENGINE
      value: "postgres"
    - name: DB_NAME
      value: "django"
    - name: DB_USER
      value: "django"
    - name: DB_PASSWORD
      value: "django"
    - name: DB_HOST
      value: "10.0.64.3"
    livenessProbe:
      httpGet:
        path: /polls/
        port: 80
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 1Gi